Weight entry QoL improvements
wger-project/flutter pull request #632
Opened 2024-09-05 19:59 UTC by sizzlesloth

## Description (Proposed Changes)

- Use current DateTime when copying WeightEntry instead of using previous weight.
- Increment buttons increment weight by 0.1 and round to one decimal place to prevent floating point accuracy (rounding) issues.

## Link to the issue : 

- Link : #628 

## Checklist

- [X] Set a 100 character limit in your editor/IDE to avoid white space diffs in the PR
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Added yourself to AUTHORS.md
- [ ] Updated/added relevant documentation (doc comments with `///`).
- [X] Added relevant reviewers.

2024-09-07 16:43 UTC, Dieterbe requested changes

2024-09-07 16:43 UTC, Dieterbe commented on lib/models/body_weight/weight_entry.dart
> +        date: date ?? DateTime.now(),
when you call copyWith(), you expect that it copies the model, and overrides those fields that are given.
therefore this change doesn't make sense. Instead, the callers should just provide whichever date they want to use (DateTime.now())

2024-09-07 16:52 UTC, Dieterbe commented
also `flutter test` is broken.

your PR is a good start, it just needs some tweaks. i will finish it.

2024-09-07 16:54 UTC, merged

2024-09-07 16:55 UTC, Dieterbe commented
@sizzlesloth thanks! i merged your changes via the PR above.

2024-09-08 13:07 UTC, sizzlesloth commented
Thank you very much! :)